const STORAGE_KEY='trustmesh-events-v2';
const LAST_KEY='trustmesh-last-v2';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
let state={route:location.hash.replace('#/','')||'overview',events:read(STORAGE_KEY,[]),result:read(LAST_KEY,null),loading:false,form:{amount:50000,country:'Unknown',new_device:true,account_age:2,velocity:6}};
const nav=[['overview','⌂','Overview'],['dashboard','◈','Dashboard'],['simulation','⚡','Simulation'],['agents','◎','Agent Center'],['audit','✓','Audit Center']];
addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'overview';render()});
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
function analyze(e){
 const fraud=clamp((e.amount>=25000?30:12)+(e.amount>=75000?12:0)+(e.new_device?22:0)+(e.country==='Unknown'?16:e.country==='Sanctioned'?30:4)+(e.account_age<=7?17:5)+(e.velocity>=4?12:e.velocity>=2?6:2));
 const risk=clamp((e.new_device?24:7)+(e.country==='Unknown'?18:e.country==='Sanctioned'?35:4)+(e.velocity>=5?27:e.velocity>=3?18:6)+(e.account_age<=7?20:5)+(e.amount>=25000?11:3));
 const compliance=e.country!=='Sanctioned'&&e.amount<100000;
 const complianceScore=compliance?8:96;
 const finalScore=clamp(fraud*.5+risk*.35+complianceScore*.15);
 const decision=finalScore>=70?'BLOCK':finalScore>=50?'REVIEW':'ALLOW';
 const confidence=clamp(72+Math.abs(finalScore-50)*.55);
 return {analyses:[
  {agent:'Fraud Agent',score:fraud,reason:`Amount, velocity, geography and account age → ${fraud}/100.`,status:'COMPLETE',scope:'transaction patterns'},
  {agent:'Risk Agent',score:risk,reason:`Device, country, velocity and behaviour → ${risk}/100.`,status:'COMPLETE',scope:'risk context'},
  {agent:'Compliance Agent',score:complianceScore,reason:compliance?'No simulated policy veto.':'Policy threshold triggered a compliance hold.',status:'COMPLETE',scope:'policy controls'}
 ],finalScore,decision,confidence,compliance};
}
async function sha256(value){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(data)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function run(){
 state.loading=true;render();
 const event={...state.form,amount:Number(state.form.amount),account_age:Number(state.form.account_age),velocity:Number(state.form.velocity),created_at:new Date().toISOString()};
 const result=analyze(event); const commitment=JSON.stringify({protocol:'TrustMesh-Audit-v2',event,result}); result.hash=await sha256(commitment);result.event=event;state.result=result;
 const item={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),amount:event.amount,decision:result.decision,score:result.finalScore,confidence:result.confidence,hash:result.hash,time:event.created_at};
 state.events=[...state.events,item].slice(-100);localStorage.setItem(STORAGE_KEY,JSON.stringify(state.events));localStorage.setItem(LAST_KEY,JSON.stringify(result));state.loading=false;location.hash='/simulation';
}
function shell(content){return `<div class="app"><aside><a class="brand" href="#/overview"><svg class="logo-svg" viewBox="0 0 64 64"><path d="M32 3 56 16v20c0 12-9 20-24 25C17 56 8 48 8 36V16L32 3Z" fill="none" stroke="#14d9ff" stroke-width="3"/><circle cx="32" cy="19" r="6" fill="#14d9ff"/><circle cx="18" cy="42" r="6" fill="#2d76ff"/><circle cx="46" cy="42" r="6" fill="#6747ff"/><circle cx="32" cy="33" r="4" fill="#fff"/><path d="M32 25v4M27 35l-7 5M37 35l7 5M24 42h16" stroke="#14d9ff" stroke-width="2"/></svg><span>TrustMesh <b>AI</b></span></a><div class="pill"><i></i> NETWORK ONLINE</div><nav>${nav.map(([k,i,l])=>`<a class="${state.route===k?'active':''}" href="#/${k}"><span>${i}</span>${l}</a>`).join('')}</nav><div class="sidefoot"><strong>Move intelligence.</strong><span>Not sensitive data.</span><small>DOJO MVP • by ElCryptoBoy</small></div></aside><main><header><div><small>SOVEREIGN INTELLIGENCE</small><h1>TrustMesh <em>AI</em></h1></div><div class="actions"><span class="secure"><i></i>Privacy-first simulation</span><a href="#/simulation" class="btn primary">Run demo →</a></div></header>${content}<div class="footer">TrustMesh AI • Hackathon MVP • No customer data • No live banking decisions</div></main></div>`}
function title(k,t,d){return `<div class="content title"><span class="kicker">${k}</span><h2>${t}</h2><p>${d}</p></div>`}
function metric(l,v,s){return `<div class="card metric"><small>${l}</small><strong>${v}</strong><em>● ${s}</em></div>`}
function info(t,d){return `<div><strong>${t}</strong><p>${d}</p></div>`}
function feature(i,t,d){return `<div class="card feature"><span class="ico">${i}</span><h4>${t}</h4><p>${d}</p></div>`}
function overview(){return `<div class="content"><section class="hero"><div><span class="kicker">COLLABORATIVE AI FOR REGULATED INDUSTRIES</span><h2>Move <b>intelligence.</b><br>Not sensitive data.</h2><p>TrustMesh AI is a sovereign intelligence layer for organizations that need collaborative decisions without centralizing sensitive records.</p><div class="row"><a class="btn primary" href="#/simulation">Launch live demo →</a><a class="btn" href="#/dashboard">Explore network</a></div><div class="notice"><strong>Demo guarantee:</strong> every simulated decision is reproducible, explainable and SHA-256 auditable. Raw transaction data remains local to this browser.</div></div></section><section class="section"><div class="sectionhead"><div><span class="kicker">CORE ADVANTAGE</span><h3>A control plane for collaborative intelligence</h3></div></div><div class="grid four">${feature('◈','Data sovereignty','Raw transaction data stays at the institution. The mesh exchanges approved intelligence signals.')}${feature('◎','Multi-agent reasoning','Fraud, risk and compliance agents analyze independently before consensus.')}${feature('⚡','Real-time ready','An edge-first design reduces the need to move sensitive records to a central model.')}${feature('✓','Auditable by design','Event + agent outputs + policy decision are committed to a cryptographic fingerprint.')}</div></section><section class="section"><div class="sectionhead"><div><span class="kicker">NETWORK ARCHITECTURE</span><h3>Three institutions. One intelligence layer.</h3></div></div><div class="grid three">${feature('01','Local agents','Each bank can run models against its own transaction context and policies.')}${feature('02','Privacy boundary','Only permitted intelligence crosses the boundary; raw records remain inside the institution.')}${feature('03','Consensus + audit','Independent signals become one policy-aware decision with an integrity commitment.')}</div></section><section class="card section"><div class="sectionhead"><div><span class="kicker">ROADMAP TO PRODUCTION</span><h3>What turns this MVP into infrastructure</h3></div></div><div class="grid four steps">${['Local model runtime','Secure aggregation','Signed policies','Ledger anchoring'].map((x,i)=>`<div><span class="kicker">0${i+1}</span><strong>${x}</strong></div>`).join('')}</div></section></div>`}
function dashboard(){const blocks=state.events.filter(e=>e.decision==='BLOCK').length;const avg=state.events.length?Math.round(state.events.reduce((a,e)=>a+e.score,0)/state.events.length):0;return `<div>${title('CONTROL PLANE','Network Dashboard','Operational view of the TrustMesh collaborative fraud simulation.')}<div class="content"><div class="grid four">${metric('Nodes connected','3','All nodes healthy')}${metric('Events analyzed',state.events.length,'Local demo ledger')}${metric('Fraud detected',blocks,'Consensus BLOCK')}${metric('Average risk',avg+'/100','Across events')}</div><div class="section grid two"><div class="card"><div class="sectionhead"><div><h3>Connected institutions</h3><p>Independent inference nodes</p></div></div>${['Bank Alpha','Bank Beta','Bank Gamma'].map(n=>`<div class="node"><div><i></i><strong>${n}</strong><small>Local inference • data retained</small></div><span class="tag">ONLINE</span></div>`).join('')}</div><div class="card"><div class="sectionhead"><div><h3>Activity feed</h3><p>Most recent decisions</p></div></div>${state.events.length?state.events.slice().reverse().slice(0,7).map(e=>`<div class="event"><i></i><div><strong>Transaction #${e.id.toString().slice(-6)}</strong><small>$${Number(e.amount).toLocaleString()} • risk ${e.score}/100 • ${e.confidence}% confidence</small></div><span class="tag">${e.decision}</span></div>`).join(''):`<div class="notice">No events yet. Launch the simulation to create your first decision.</div>`}</div></div><div class="card section"><div class="sectionhead"><div><h3>Why the architecture matters</h3><p>Enterprise design principles</p></div></div><div class="grid three">${info('Federated by default','A production node would run institution-local inference and expose only privacy-approved signals.')}${info('Policy-aware','Compliance can veto, escalate or approve independently from model scores.')}${info('Verifiable','A decision can be replayed and its commitment checked against the original event.')}</div></div></div></div>`}
function simulation(){const r=state.result;return `<div>${title('EVENT SIMULATOR','Fraud Decision Lab','Create a suspicious transfer and watch four logical agents collaborate.')}<div class="content"><div class="card"><div class="sectionhead"><div><h3>Transaction payload</h3><p>In production this payload would be processed by the bank-local node.</p></div><span class="tag">LOCAL DATA</span></div><div class="form"><label class="field"><span>Amount USD</span><input id="amount" type="number" min="1" value="${state.form.amount}"></label><label class="field"><span>Country</span><select id="country"><option>Unknown</option><option>Argentina</option><option>United States</option><option>Sanctioned</option></select></label><label class="field"><span>New device</span><select id="device"><option value="true" ${state.form.new_device?'selected':''}>Yes</option><option value="false" ${!state.form.new_device?'selected':''}>No</option></select></label><label class="field"><span>Account age / days</span><input id="age" type="number" min="0" value="${state.form.account_age}"></label><label class="field"><span>Velocity / hour</span><input id="velocity" type="number" min="0" value="${state.form.velocity}"></label></div><div class="row"><button id="run" class="btn primary">${state.loading?'Running agents…':'Generate Fraud Event →'}</button><a class="btn" href="#/agents">Open Agent Center →</a></div></div>${r?resultView(r):''}</div></div>`}
function resultView(r){return `<div class="section grid two"><div class="card"><div class="sectionhead"><div><h3>Consensus Decision</h3><p>Final policy-aware output</p></div><span class="tag">${r.confidence}% CONFIDENCE</span></div><div class="decision ${r.decision==='BLOCK'?'block':''}"><span class="kicker">FINAL ACTION</span><div class="big">${r.decision} TRANSACTION</div><p>Composite risk score <strong>${r.finalScore}/100</strong></p><div class="risk"><span style="width:${r.finalScore}%"></span></div><small>Signals are deterministic for the demo. Production models would be institution-specific.</small></div></div><div class="card"><div class="sectionhead"><div><h3>Integrity proof</h3><p>SHA-256 audit commitment</p></div><span class="tag">VERIFIABLE</span></div><div class="hash">${r.hash}</div><div class="notice">The hash commits the event, agent results and TrustMesh audit protocol. Changing any input changes the fingerprint.</div><a class="btn" style="margin-top:12px" href="#/audit">View Audit Trail →</a></div></div><div class="card section"><div class="sectionhead"><div><h3>Agent reasoning</h3><p>Independent signals → consensus</p></div></div>${agents(r)}</div>`}
function agents(r){const a=r?.analyses||[{agent:'Fraud Agent',score:91,reason:'Amount, velocity, geography and account age.',status:'READY'},{agent:'Risk Agent',score:78,reason:'Device, country, velocity and behaviour.',status:'READY'},{agent:'Compliance Agent',score:12,reason:'Regulatory and policy constraints.',status:'READY'}];const all=[...a,{agent:'Consensus Agent',score:r?.finalScore??89,reason:'Weighted policy-aware decision across independent signals.',status:r?'COMPLETE':'READY'}];return all.map(x=>`<div class="agent"><div><strong>${x.agent}</strong><small>${x.reason}</small></div><div class="bar"><span style="width:${x.score}%"></span></div><strong>${x.score}</strong><em>${x.status}</em></div>`).join('')}
function agentPage(){return `<div>${title('MULTI-AGENT ORCHESTRATION','Agent Center','A visual control plane showing how independent nodes contribute signals before a final consensus.')}<div class="content"><div class="card diagram"><div class="ring"></div><div class="core">TRUST<br><b>MESH</b><br>CONSENSUS</div><div class="bubble top">Bank Alpha<small>local node</small></div><div class="bubble left">Bank Beta<small>local node</small></div><div class="bubble right">Bank Gamma<small>local node</small></div></div><div class="card section"><div class="sectionhead"><div><h3>Current agent state</h3><p>Specialized reasoning layer</p></div></div>${agents(state.result)}</div><div class="grid three section">${info('Independent signals','Fraud and risk are separate assessments. No single score silently controls the whole decision.')}${info('Compliance veto','Policy controls can stop or escalate a transaction even when model risk is low.')}${info('Production upgrade','Replace this deterministic simulation with local models, secure aggregation and signed agent attestations.')}</div></div></div>`}
function audit(){return `<div>${title('VERIFIABLE HISTORY','Audit Center','A tamper-evident view of every simulated decision generated by the mesh.')}<div class="content"><div class="card"><div class="sectionhead"><div><h3>Decision ledger</h3><p>${state.events.length} stored event${state.events.length===1?'':'s'}</p></div><button id="clear" class="btn">Clear demo data</button></div>${state.events.length?state.events.slice().reverse().map(e=>`<div class="audit"><div><strong>${e.decision}</strong><small>Score ${e.score}/100 • ${e.confidence}%</small></div><div class="hash">${e.hash}</div><div>${new Date(e.time).toLocaleString()}</div></div>`).join(''):`<div class="notice">Run a fraud event first. Its decision, score, timestamp and hash will appear here.</div>`}</div><div class="grid three section">${info('Integrity','SHA-256 makes post-decision alteration detectable.')}${info('Explainability','The commitment includes the event and independent agent outputs.')}${info('Production anchor','A future deployment can anchor hashes to a permissioned ledger, public chain or WORM storage.')}</div></div></div>`}
function render(){let c=state.route==='dashboard'?dashboard():state.route==='simulation'?simulation():state.route==='agents'?agentPage():state.route==='audit'?audit():overview();document.getElementById('app').innerHTML=shell(c);if(state.route==='simulation')document.getElementById('run')?.addEventListener('click',()=>{state.form.amount=+document.getElementById('amount').value;state.form.country=document.getElementById('country').value;state.form.new_device=document.getElementById('device').value==='true';state.form.account_age=+document.getElementById('age').value;state.form.velocity=+document.getElementById('velocity').value;run()});if(state.route==='audit')document.getElementById('clear')?.addEventListener('click',()=>{state.events=[];state.result=null;localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LAST_KEY);render()})}
render();
